Основы JS. Примитивные типы данных
js-tasks-ru/js-20210309-2_evg-dev pull request #2
Opened 2021-03-16 08:12 UTC by e-frontender

2021-03-16 08:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-16 20:08 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  switch (param) {
пожалуйста подскажите почему тут использован `switch...case`?

2021-03-16 20:08 UTC, dosandk requested changes
необходимо дать ответ на вопрос

2021-03-16 20:12 UTC, e-frontender commented on 02-javascript-data-types/1-sort-strings/index.js
> +  switch (param) {
> пожалуйста подскажите почему тут использован `switch...case`?

Здравствуйте, я сегодня поменял группу, писал об этом в Slack, до этого я не смог понять как решить задание, это - подсмотренный ответ, из всех 3х заданий этого модуля я понял только одно из всех.

2021-03-22 10:14 UTC, dosandk approved these changes

2021-03-22 10:14 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2021-03-23 09:13 UTC, dosandk approved these changes

2021-03-23 09:13 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2021-03-24 21:50 UTC, dosandk commented
@e-frontender пожалуйста решите конфликты

2021-04-01 10:11 UTC, dosandk approved these changes

2021-04-01 10:11 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2021-04-03 17:04 UTC, dosandk commented
@e-frontender пожалуйста решите конфликты

2023-01-24 19:26 UTC, closed without merging